### ISSUE TITLE
Hosting on an ESP32

### ISSUE THREAD

**Issue by NorthernMan54** [jozefnad/balboa-spa#1]
I'm in the process of coding an ESP 32 with a T-Panel display https://www.lilygo.cc/en-ca/products/t5-4-7-inch-e-paper-v2-3?srsltid=AfmBOoqGyGQo8zs4eGypdadbyr5RbfBxRUK-hock2-Yf6sNINq-4DQ0Y, to work as a in house display of the SPA status.  And was going include a web site for local access and control.

Do you think I could host your website code on the ESP32 ?  And have the data retrieved locally from the ESP32 rather than the cloud API?

https://github.com/NorthernMan54/esp32_balboa_panel

**Comment by jozefnad** [comment]
of course, but you need rewrite code to work with local ESP data

**Comment by NorthernMan54** [comment]
I was just going to change the URL to point to my ESP32, and have a web server mimic the balboa endpoint.  I looked at the interface, and it is the spa’s binary format wrapped in xml.  Pretty simple, as I already have the binary data.

am thinking the only change should be the url within your code base. And if it’s that simple, I may submit a PR to support it.

**Comment by jozefnad** [comment]
If your ESP has same data structure as Balboa cloud API you can change just the endpoint, otherwise you need to make more changes on ESP or here.

**Comment by jozefnad** [comment]
Please give a star if you like it :)
